/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutricionista_g52.vistas;

import java.text.Normalizer;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import nutricionista_g52.accesoADatos.ComidaData;
import nutricionista_g52.entidades.Comida;
import nutricionista_g52.vistas.excepciones.CampoVacioException;
import nutricionista_g52.vistas.excepciones.RangoNumericoException;
import nutricionista_g52.vistas.excepciones.TipoDeDatoException;

/**
 *
 * @author Matías Pacheco
 */
public class EditarComidaView extends javax.swing.JInternalFrame {
    private ComidaData comiData;
    private Comida comida;
    
    /**
     * Creates new form ComidasView
     */
    public EditarComidaView() {
        initComponents();
    }
    
    public EditarComidaView(Comida comida){
        initComponents();
        this.comiData = new ComidaData();
        this.comida = comida;
        llenarCamposConDatosDeLaComida();
    }
    
//---------- Por Defecto ----------
    private void llenarCamposConDatosDeLaComida(){
        setearTextoEnCampoNro(1, comida.getNombre());
        setearTextoEnCampoNro(2, comida.getDetalle());
        setearTextoEnCampoNro(3, String.valueOf(comida.getCantCalorias()));
    }
    
    private String removerAcentos(String cadena) {
        String normalizado = Normalizer.normalize(cadena, Normalizer.Form.NFD);
        Pattern patron = Pattern.compile("\\p{InCombiningDiacriticalMarks}+");
        return patron.matcher(normalizado).replaceAll("");
    }
    
//---------- Métodos Reune Métodos (método atajo)----------
    private void setearTextoEnCampoNro(int opcion, String texto){
        switch(opcion){
            case 1:{ jTexFiNombre.setText(texto); break; } 
            case 2:{ jTexFiDetalle.setText(texto); break; } 
            case 3:{ jTexFiCalorias.setText(texto); break; } 
            case 4:{
                jTexFiNombre.setText(texto); 
                jTexFiDetalle.setText(texto); 
                jTexFiCalorias.setText(texto);
                break;
            } 
        }
    }
    
    private void setearTextoEnEtiquetaNro(int opcion, String texto){
        switch(opcion){
            case 1:{ jLabJTFNombre.setText(texto); break; }
            case 2:{ jLabJTFDetalle.setText(texto); break; }
            case 3:{ jLabJTFCalorias.setText(texto); break; }
            case 4:{
                jLabJTFNombre.setText(texto);
                jLabJTFDetalle.setText(texto);
                jLabJTFCalorias.setText(texto);
                break;
            }
        }
    }

//---------- Excepciones ----------
    private void excepcionCampoVacio(String dato) throws CampoVacioException {
        if(dato.isEmpty()){
            throw new CampoVacioException("Campo/s vacio");
        }
    }
    
    private void excepcionTipoDeDato(String dato, String expresionRegular) throws TipoDeDatoException {
        if(!dato.matches(expresionRegular)){
            throw new TipoDeDatoException("Tipo de dato invalido. Ingrese unicamente ");
        }
    }
    
    private void excepcionRangoNumerico(int num) throws RangoNumericoException {
        if(num < 1 || num > 10000){
            throw new RangoNumericoException("Solo se permiten valores entre 1 y 10.000");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTexFiNombre = new javax.swing.JTextField();
        jTexFiDetalle = new javax.swing.JTextField();
        jTexFiCalorias = new javax.swing.JTextField();
        jLabJTFNombre = new javax.swing.JLabel();
        jLabJTFDetalle = new javax.swing.JLabel();
        jLabJTFCalorias = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButGuardar = new javax.swing.JButton();
        jButCancelar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar COMIDA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(12, 12, 12))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Detalle");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Calorias");

        jTexFiNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexFiNombreKeyReleased(evt);
            }
        });

        jTexFiDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexFiDetalleKeyReleased(evt);
            }
        });

        jTexFiCalorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexFiCaloriasKeyReleased(evt);
            }
        });

        jLabJTFNombre.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        jLabJTFDetalle.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        jLabJTFCalorias.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTexFiCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabJTFCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabJTFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabJTFDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTexFiNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTexFiDetalle, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(12, 12, 12))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexFiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabJTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTexFiDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabJTFDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTexFiCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabJTFCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jButGuardar.setText("Guardar");
        jButGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGuardarActionPerformed(evt);
            }
        });

        jButCancelar.setText("Cancelar");
        jButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jButGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButCancelar)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCancelar)
                    .addComponent(jButGuardar))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButCancelarActionPerformed

    private void jButGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGuardarActionPerformed
        // TODO add your handling code here:
        
        String ingSolo = "letras";
        try{
            String nombre = jTexFiNombre.getText(); excepcionCampoVacio(nombre); excepcionTipoDeDato(nombre, "^[a-zA-ZÀ-ÖØ-öø-ÿ ]*$");
            ingSolo+= ", números y signos permitidos (.,¡!;:-'/\"()%*)";
            String detalle = jTexFiDetalle.getText(); excepcionCampoVacio(detalle); excepcionTipoDeDato(detalle, 
                    "^[\\p{L}\\p{N}.¡!;:,'\"/%()* -]*$");
            String caloriasCad = jTexFiCalorias.getText(); excepcionCampoVacio(caloriasCad);
            int calorias = (int) Long.parseLong(caloriasCad); excepcionRangoNumerico(calorias);
            boolean estado = true;

            Comida comi = new Comida(nombre, detalle, calorias, estado);
            comi.setIdComida(this.comida.getIdComida());
            
            if(comiData.modificarComida(comi)){
                setearTextoEnCampoNro(4, "");
                
                this.dispose();
            }
        } catch(CampoVacioException cve){
            JOptionPane.showMessageDialog(null, cve.getMessage()+". Llene todos los campos indicados", "  Mensaje", 1);
        } catch(TipoDeDatoException tdde){
            JOptionPane.showMessageDialog(null, tdde.getMessage()+ingSolo, "  Mensaje", 1);
        } catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Ingrese unicamente números enteros", "  Mensaje", 1);
        } catch(RangoNumericoException rne){
            JOptionPane.showMessageDialog(null, rne.getMessage(), "  Mensaje", 1);
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButGuardarActionPerformed

    private void jTexFiNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexFiNombreKeyReleased
        // TODO add your handling code here:
        setearTextoEnEtiquetaNro(1, "");
        
        try{
            String nombre = jTexFiNombre.getText(); excepcionTipoDeDato(nombre, "^[a-zA-ZÀ-ÖØ-öø-ÿ ]*$");
            
            if(comiData.buscarComidaPorNombreBoolean(nombre) && !comida.getNombre().equalsIgnoreCase(removerAcentos(nombre))){
                setearTextoEnEtiquetaNro(1, "el nombre está en uso");
            }
        } catch(TipoDeDatoException tdde){
            setearTextoEnEtiquetaNro(1, "solo letras");
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTexFiNombreKeyReleased

    private void jTexFiDetalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexFiDetalleKeyReleased
        // TODO add your handling code here:
        setearTextoEnEtiquetaNro(2, "");
        
        try{
            String detalle = jTexFiDetalle.getText(); excepcionTipoDeDato(detalle, "^[\\p{L}\\p{N}.¡!;:,'\"/%()* -]*$");
        } catch(TipoDeDatoException tdde){
            setearTextoEnEtiquetaNro(2, "solo letras, números y signos (.,¡!;:-'/\"()%*)");
        }
    }//GEN-LAST:event_jTexFiDetalleKeyReleased

    private void jTexFiCaloriasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexFiCaloriasKeyReleased
        // TODO add your handling code here:
        setearTextoEnEtiquetaNro(3, "");
        
        try{
            String caloriasCad = jTexFiCalorias.getText(); excepcionCampoVacio(caloriasCad);
            int calorias = (int) Long.parseLong(caloriasCad); excepcionRangoNumerico(calorias);
        } catch(CampoVacioException cve){
            //Capturo está excepción para evitar que intente parsear una cadena vacia
        } catch(NumberFormatException nfe){
            setearTextoEnEtiquetaNro(3, "solo números enteros");
        } catch(RangoNumericoException rne){
            setearTextoEnEtiquetaNro(3, "desde 1 hasta 10.000");
        }
    }//GEN-LAST:event_jTexFiCaloriasKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButCancelar;
    private javax.swing.JButton jButGuardar;
    private javax.swing.JLabel jLabJTFCalorias;
    private javax.swing.JLabel jLabJTFDetalle;
    private javax.swing.JLabel jLabJTFNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTexFiCalorias;
    private javax.swing.JTextField jTexFiDetalle;
    private javax.swing.JTextField jTexFiNombre;
    // End of variables declaration//GEN-END:variables
}
