/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutricionista_g52.vistas;

import javax.swing.JOptionPane;
import nutricionista_g52.accesoADatos.PacienteData;
import nutricionista_g52.entidades.Paciente;
import nutricionista_g52.vistas.excepciones.CampoVacioException;
import nutricionista_g52.vistas.excepciones.RangoNumericoException;
import nutricionista_g52.vistas.excepciones.TipoDeDatoException;

/**
 *
 * @author Matías Pacheco
 */
public class NuevoPacienteView extends javax.swing.JInternalFrame {
    private PacienteData pacData;

    /**
     * Creates new form ComidasView
     */
    public NuevoPacienteView() {
        initComponents();
        this.pacData = new PacienteData();
    }
    
//---------- Por defecto ---------- //Dejar para ultimo momento
//    private void textoEjemploPorDefecto(){
//        jTexFiDni.setText("12345678");
//    }
    
//----------  ----------
    private void setearTextoEnCampoNro(int opcion, String texto){
        switch(opcion){
            case 1:{ jTexFiDni.setText(texto); break; }
            case 2:{ jTexFiApellido.setText(texto); break; }
            case 3:{ jTexFiNombre.setText(texto); break; }
            case 4:{ jTexFiDomicilio.setText(texto); break; }
            case 5:{ jTexFiTelefono.setText(texto); break; }
            case 6:{
                jTexFiDni.setText(texto);
                jTexFiApellido.setText(texto);
                jTexFiNombre.setText(texto);
                jTexFiDomicilio.setText(texto);
                jTexFiTelefono.setText(texto);
                break;
            }
        }
    }
    
    private void setearTextoEnEtiquetaNro(int opcion, String texto){
        switch(opcion){
            case 1:{ jLabJTFDni.setText(texto); break;}
            case 2:{ jLabJTFApellido.setText(texto); break;}
            case 3:{ jLabJTFNombre.setText(texto); break;}
            case 4:{ jLabJTFDomicilio.setText(texto); break;}
            case 5:{ jLabJTFTelefono.setText(texto); break;}
        }
    }
    
//---------- Excepciones ----------
    private void excepcionCampoVacio(String dato) throws CampoVacioException {
        if(dato.isEmpty()){
            throw new CampoVacioException("Campo/s vacio");
        }
    }
    
    private void excepcionRangoNumerico(long num, long rangoMenor, long rangoMayor) throws RangoNumericoException {
        if(num < rangoMenor || num > rangoMayor){
            throw new RangoNumericoException("Solo se permiten valores entre \n"+rangoMenor+" "
                    + "y "+rangoMayor+"");
        }
    }
    
    private void excepcionRangoNumerico(int num, int rangoMenor, int rangoMayor) throws RangoNumericoException {
        if(num < rangoMenor || num > rangoMayor){
            throw new RangoNumericoException("Solo se permiten valores entre \n"+rangoMenor+" "
                    + "y "+rangoMayor+"");
        }
    }
    
    private void excepcionTipoDeDato(String dato, String expresionRegular) throws TipoDeDatoException {
        if(!dato.matches(expresionRegular)){
            throw new TipoDeDatoException("Tipo de dato u orden de dato invalido. Ingrese unicamente ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTexFiDni = new javax.swing.JTextField();
        jTexFiApellido = new javax.swing.JTextField();
        jTexFiNombre = new javax.swing.JTextField();
        jTexFiDomicilio = new javax.swing.JTextField();
        jTexFiTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabJTFDni = new javax.swing.JLabel();
        jLabJTFApellido = new javax.swing.JLabel();
        jLabJTFNombre = new javax.swing.JLabel();
        jLabJTFDomicilio = new javax.swing.JLabel();
        jLabJTFTelefono = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButGuardar = new javax.swing.JButton();
        jButCancelar = new javax.swing.JButton();
        jButLimpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo PACIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(12, 12, 12))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("DNI");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Domicilio");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Teléfono");

        jTexFiDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexFiDniKeyReleased(evt);
            }
        });

        jTexFiApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexFiApellidoKeyReleased(evt);
            }
        });

        jTexFiNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexFiNombreKeyReleased(evt);
            }
        });

        jTexFiDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexFiDomicilioKeyReleased(evt);
            }
        });

        jTexFiTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexFiTelefonoKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");

        jLabJTFDni.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        jLabJTFApellido.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        jLabJTFNombre.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        jLabJTFDomicilio.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        jLabJTFTelefono.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabJTFApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabJTFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jTexFiDni, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel10)
                                            .addGap(102, 102, 102))
                                        .addComponent(jTexFiApellido)
                                        .addComponent(jTexFiNombre)
                                        .addComponent(jLabJTFDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(28, 28, 28)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTexFiDomicilio)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jTexFiTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabJTFTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabJTFDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTexFiDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(0, 0, 0)
                .addComponent(jLabJTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexFiApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(0, 0, 0)
                .addComponent(jLabJTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTexFiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(0, 0, 0)
                .addComponent(jLabJTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTexFiDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(0, 0, 0)
                .addComponent(jLabJTFDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTexFiTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(0, 0, 0)
                .addComponent(jLabJTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButGuardar.setText("Guardar");
        jButGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGuardarActionPerformed(evt);
            }
        });

        jButCancelar.setText("Cancelar");
        jButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelarActionPerformed(evt);
            }
        });

        jButLimpiar.setText("Limpiar");
        jButLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jButCancelar)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCancelar)
                    .addComponent(jButGuardar)
                    .addComponent(jButLimpiar))
                .addGap(12, 12, 12))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("campos obligatorios");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(227, 227, 227))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButCancelarActionPerformed

    private void jButGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGuardarActionPerformed
        // TODO add your handling code here:
        
        String ingSolo = "letras";
        try{
            String dniCad = jTexFiDni.getText(); excepcionCampoVacio(dniCad);
            int dni = (int) Long.parseLong(dniCad); excepcionRangoNumerico(dni, 1000000, 99999999);
            String apellido = jTexFiApellido.getText(); excepcionCampoVacio(apellido); excepcionTipoDeDato(apellido, "^[a-zA-ZÀ-ÖØ-öø-ÿ ]*$");
            String nombre = jTexFiNombre.getText(); excepcionCampoVacio(nombre); excepcionTipoDeDato(nombre, "^[a-zA-ZÀ-ÖØ-öø-ÿ ]*$");
            ingSolo+= " y números";
            String domicilio = jTexFiDomicilio.getText(); excepcionCampoVacio(domicilio); excepcionTipoDeDato(domicilio, 
                    "^([a-zA-ZÀ-ÖØ-öø-ÿ]+ ?)+ \\d+$");
            ingSolo = "números";
            String telefono = jTexFiTelefono.getText(); excepcionCampoVacio(telefono); excepcionTipoDeDato(telefono, "^[0-9\\s]*$");
            long telefonoNro = Long.parseLong(telefono.replace(" ", "")); excepcionRangoNumerico(telefonoNro, 1000000000L, 9999999999L);
            boolean estado = true;

            Paciente paciente = new Paciente(dni, apellido, nombre, domicilio, telefono, estado);

            if(pacData.guardarPaciente(paciente)){
                setearTextoEnCampoNro(6, "");
                
                this.dispose();
            }
        } catch(CampoVacioException cve){
            JOptionPane.showMessageDialog(null, cve.getMessage()+". Llene todos los campos indicados", "  Mensaje", 1);
        } catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Ingrese unicamente el número de documento sin puntuaciones", 
                    "  Mensaje", 1);
        } catch(RangoNumericoException rne){
            JOptionPane.showMessageDialog(null, "Número fuera de rango. "+rne.getMessage(), "  Mensaje", 1);
        } catch(TipoDeDatoException tdde){
            JOptionPane.showMessageDialog(null, tdde.getMessage()+ingSolo+".\nY respete el orden de entrada de los mismos",
                    "  Mensaje", 1);
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButGuardarActionPerformed

    private void jButLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButLimpiarActionPerformed
        // TODO add your handling code here:
        
        setearTextoEnCampoNro(6, "");
    }//GEN-LAST:event_jButLimpiarActionPerformed

    private void jTexFiDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexFiDniKeyReleased
        // TODO add your handling code here:
        setearTextoEnEtiquetaNro(1, "");
        
        try{
            String dniCad = jTexFiDni.getText(); excepcionCampoVacio(dniCad);
            int dni = (int) Long.parseLong(dniCad); excepcionRangoNumerico(dni, 1000000, 99999999);
            
            if(pacData.buscarPacientePorDni(dni)){
                setearTextoEnEtiquetaNro(1, "el número está en uso");
            }
        } catch(CampoVacioException cve){
            //Capturo está excepción para evitar que intente parsear una cadena vacia
        } catch(NumberFormatException nfe){
            setearTextoEnEtiquetaNro(1, "solo números");
        } catch(RangoNumericoException rne){
            setearTextoEnEtiquetaNro(1, "desde 1.000.000 hasta 99.999.999");
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTexFiDniKeyReleased

    private void jTexFiApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexFiApellidoKeyReleased
        // TODO add your handling code here:
        setearTextoEnEtiquetaNro(2, "");
        
        try{
            String apellido = jTexFiApellido.getText(); excepcionTipoDeDato(apellido, "^[a-zA-ZÀ-ÖØ-öø-ÿ ]*$");
        } catch(TipoDeDatoException tdde){
            setearTextoEnEtiquetaNro(2, "solo letras");
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTexFiApellidoKeyReleased

    private void jTexFiNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexFiNombreKeyReleased
        // TODO add your handling code here:
        setearTextoEnEtiquetaNro(3, "");
        
        try{
            String nombre = jTexFiNombre.getText(); excepcionTipoDeDato(nombre, "^[a-zA-ZÀ-ÖØ-öø-ÿ ]*$");
        } catch(TipoDeDatoException tdde){
            setearTextoEnEtiquetaNro(3, "solo letras");
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTexFiNombreKeyReleased

    private void jTexFiDomicilioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexFiDomicilioKeyReleased
        // TODO add your handling code here:
        setearTextoEnEtiquetaNro(4, "");
        
        try{
            String domicilio = jTexFiDomicilio.getText(); excepcionCampoVacio(domicilio); excepcionTipoDeDato(domicilio, 
                    "^([a-zA-ZÀ-ÖØ-öø-ÿ]+ ?)+ \\d+$");
        } catch(CampoVacioException cve){
            //Capturo está excepción para evitar mostrar el mensaje en el caso de que el usuario borre lo que ingreso
        } catch(TipoDeDatoException tdde){
            setearTextoEnEtiquetaNro(4, "calle número (ej: calle 123)");
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTexFiDomicilioKeyReleased

    private void jTexFiTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexFiTelefonoKeyReleased
        // TODO add your handling code here:
        setearTextoEnEtiquetaNro(5, "");
        
        try{   
            String telefono = jTexFiTelefono.getText(); excepcionCampoVacio(telefono); excepcionTipoDeDato(telefono, "^[0-9\\s]*$");
            long telefonoNro = Long.parseLong(telefono.replace(" ", "")); excepcionRangoNumerico(telefonoNro, 1000000000L, 9999999999L);
        
            if(pacData.buscarPacientePorTelefono(telefono)){
                setearTextoEnEtiquetaNro(5, "el número está en uso");
            }
        } catch(CampoVacioException cve){
            //Capturo está excepción para evitar que intente parsear una cadena vacia
        } catch(TipoDeDatoException tdde){
            setearTextoEnEtiquetaNro(5, "solo números");
        } catch(RangoNumericoException rne){
            setearTextoEnEtiquetaNro(5, "desde 100 000 0000 hasta 999 9999 9999");
        }
    }//GEN-LAST:event_jTexFiTelefonoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButCancelar;
    private javax.swing.JButton jButGuardar;
    private javax.swing.JButton jButLimpiar;
    private javax.swing.JLabel jLabJTFApellido;
    private javax.swing.JLabel jLabJTFDni;
    private javax.swing.JLabel jLabJTFDomicilio;
    private javax.swing.JLabel jLabJTFNombre;
    private javax.swing.JLabel jLabJTFTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTexFiApellido;
    private javax.swing.JTextField jTexFiDni;
    private javax.swing.JTextField jTexFiDomicilio;
    private javax.swing.JTextField jTexFiNombre;
    private javax.swing.JTextField jTexFiTelefono;
    // End of variables declaration//GEN-END:variables
}
